---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999

