---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emojivoto-run-as-root-because-testing
rules:
  - apiGroups:
    - policy
    resourceNames:
    - privileged
    resources:
    - podsecuritypolicies
    verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emojivoto-basic-privileged
  namespace: emojivoto
subjects:
- kind: ServiceAccount
  name: emoji
- kind: ServiceAccount
  name: voting
- kind: ServiceAccount
  name: web
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: emojivoto-run-as-root-because-testing
  apiGroup: rbac.authorization.k8s.io
