---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: web-svc
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  template:
    spec:
      containers:
      - name: voting-svc
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
spec:
  template:
    spec:
      containers:
      - name: emoji-svc
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
      securityContext:
        runAsUser: 999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: vote-bot
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
      securityContext:
        runAsUser: 999

